x=input("enter the value of x:")
y=input("enter the value of y:")
x=int(x)
y=int(y)
print("~~~~ARITHEMTIC OPERATORS~~~~")
print('x + y =',x+y)
print('x - y =',x-y)
print('x * y =',x*y)
print('x / y =',x/y)
print('x // y =',x//y)
print("~~~~RELATIONAL OPERATORS~~~~")
print('x > y is',x>y)
print('x < y is',x<y)
print('x == y is',x==y)
print('x != y is',x!=y)
print('x >= y is',x>=y)
print('x <= y is',x<=y)
print("~~~~LOGICAL OPERATORS~~~~")
x = True
y = False

print('x and y is',x and y)
print('x or y is',x or y)
print('not x is',not x)